import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Sanguine",
  description: "Generated by create next app",
};

const PrivacyPolicy = () => {
  return (
    <div>
      <p>Privacy Policy</p>
    </div>
  );
};

export default PrivacyPolicy;
