import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Sanguine",
  description: "Generated by create next app",
};

const TermsOfService = () => {
  return (
    <div>
      <p>Terms of service</p>
    </div>
  );
};

export default TermsOfService;
