import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shipping Policy - Sanguine",
  description: "Generated by create next app",
};

const ShippingPolicy = () => {
    return ( 
        <div>
            <p>Shipping Policy</p>
        </div>
     );
}
 
export default ShippingPolicy;