import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Refund Policy - Sanguine",
  description: "Generated by create next app",
};

const RefundPolicy = () => {
  return (
    <div>
      <p>Refund Policy</p>
    </div>
  );
};

export default RefundPolicy;
